### ISSUE TITLE
AttributeError: module 'mujoco.mjx' has no attribute 'put_model'

### ISSUE THREAD

**Issue by TianleLiu0303** [FLAIROx/jaxirl#1]
Visible devices [StreamExecutorGpuDevice(id=0, process_index=0, slice_index=0)]
Traceback (most recent call last):
  File "/home/ltl/My_Projects_Python/IRL/jaxirl/jaxirl/irl/main.py", line 272, in <module>
    main(es_config)
  File "/home/ltl/My_Projects_Python/IRL/jaxirl/jaxirl/irl/main.py", line 36, in main
    env, env_params, original_training_config = get_env(es_config["env"])
  File "/home/ltl/My_Projects_Python/IRL/jaxirl/jaxirl/utils/env_utils.py", line 19, in get_env
    env, env_params = BraxGymnaxWrapper(env_name), None
  File "/home/ltl/My_Projects_Python/IRL/jaxirl/jaxirl/training/wrappers.py", line 183, in __init__
    env = envs.get_environment(env_name=env_name, backend=backend)
  File "/home/ltl/anaconda3/envs/jaxirl/lib/python3.10/site-packages/brax/envs/__init__.py", line 63, in get_environment
    return _envs[env_name](**kwargs)
  File "/home/ltl/anaconda3/envs/jaxirl/lib/python3.10/site-packages/brax/envs/ant.py", line 162, in __init__
    sys = mjcf.load(path)
  File "/home/ltl/anaconda3/envs/jaxirl/lib/python3.10/site-packages/brax/io/mjcf.py", line 520, in load
    return load_model(mj)
  File "/home/ltl/anaconda3/envs/jaxirl/lib/python3.10/site-packages/brax/io/mjcf.py", line 448, in load_model
    mjx_model = mjx.put_model(mj)
AttributeError: module 'mujoco.mjx' has no attribute 'put_model'

**Comment by feiden** [comment]
I think, there is a problem in the requirements.txt. It specificies mujoco=3.0.0, but put_model exists only in later versions. You need to replace this line with just "mujoco" and start setup with a new environment and it should work. Note, that upgrading mujoco did not work for me, idk why.
