### ISSUE TITLE
AttributeError: module 'jax' has no attribute 'tree'

### ISSUE THREAD

**Issue by TianleLiu0303** [FLAIROx/jaxirl#2]
Visible devices [StreamExecutorGpuDevice(id=0, process_index=0, slice_index=0)]
Traceback (most recent call last):
  File "/home/ltl/My_Projects_Python/IRL/jaxirl/jaxirl/irl/main.py", line 272, in <module>
    main(es_config)
  File "/home/ltl/My_Projects_Python/IRL/jaxirl/jaxirl/irl/main.py", line 36, in main
    env, env_params, original_training_config = get_env(es_config["env"])
  File "/home/ltl/My_Projects_Python/IRL/jaxirl/jaxirl/utils/env_utils.py", line 19, in get_env
    env, env_params = BraxGymnaxWrapper(env_name), None
  File "/home/ltl/My_Projects_Python/IRL/jaxirl/jaxirl/training/wrappers.py", line 183, in __init__
    env = envs.get_environment(env_name=env_name, backend=backend)
  File "/home/ltl/anaconda3/envs/evil/lib/python3.10/site-packages/brax/envs/__init__.py", line 63, in get_environment
    return _envs[env_name](**kwargs)
  File "/home/ltl/anaconda3/envs/evil/lib/python3.10/site-packages/brax/envs/ant.py", line 162, in __init__
    sys = mjcf.load(path)
  File "/home/ltl/anaconda3/envs/evil/lib/python3.10/site-packages/brax/io/mjcf.py", line 519, in load
    return load_model(mj)
  File "/home/ltl/anaconda3/envs/evil/lib/python3.10/site-packages/brax/io/mjcf.py", line 346, in load_model
    link = jax.tree.map(lambda x: x[1:].copy(), link)
AttributeError: module 'jax' has no attribute 'tree'

**Comment by feiden** [comment]
I think the same is true here as with mujoco. I have it running with jax==0.4.38 instead and that works like a charm ...

**Comment by yangzhao-666** [comment]
I downgraded brax to 0.9.4 and it works now.
